/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as PratikBilgilerRouteImport } from './routes/pratik-bilgiler'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as HizmetBolgeleriRouteImport } from './routes/hizmet-bolgeleri'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as HizmetBolgeleriBolgeRouteImport } from './routes/hizmet-bolgeleri/$bolge'

const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const PratikBilgilerRoute = PratikBilgilerRouteImport.update({
  id: '/pratik-bilgiler',
  path: '/pratik-bilgiler',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetBolgeleriRoute = HizmetBolgeleriRouteImport.update({
  id: '/hizmet-bolgeleri',
  path: '/hizmet-bolgeleri',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetBolgeleriBolgeRoute = HizmetBolgeleriBolgeRouteImport.update({
  id: '/$bolge',
  path: '/$bolge',
  getParentRoute: () => HizmetBolgeleriRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hizmet-bolgeleri': typeof HizmetBolgeleriRouteWithChildren
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/pratik-bilgiler': typeof PratikBilgilerRoute
  '/urunler': typeof UrunlerRoute
  '/hizmet-bolgeleri/$bolge': typeof HizmetBolgeleriBolgeRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hizmet-bolgeleri': typeof HizmetBolgeleriRouteWithChildren
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/pratik-bilgiler': typeof PratikBilgilerRoute
  '/urunler': typeof UrunlerRoute
  '/hizmet-bolgeleri/$bolge': typeof HizmetBolgeleriBolgeRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hizmet-bolgeleri': typeof HizmetBolgeleriRouteWithChildren
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/pratik-bilgiler': typeof PratikBilgilerRoute
  '/urunler': typeof UrunlerRoute
  '/hizmet-bolgeleri/$bolge': typeof HizmetBolgeleriBolgeRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hizmet-bolgeleri'
    | '/hizmetler'
    | '/iletisim'
    | '/pratik-bilgiler'
    | '/urunler'
    | '/hizmet-bolgeleri/$bolge'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hizmet-bolgeleri'
    | '/hizmetler'
    | '/iletisim'
    | '/pratik-bilgiler'
    | '/urunler'
    | '/hizmet-bolgeleri/$bolge'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/hizmet-bolgeleri'
    | '/hizmetler'
    | '/iletisim'
    | '/pratik-bilgiler'
    | '/urunler'
    | '/hizmet-bolgeleri/$bolge'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HizmetBolgeleriRoute: typeof HizmetBolgeleriRouteWithChildren
  HizmetlerRoute: typeof HizmetlerRoute
  IletisimRoute: typeof IletisimRoute
  PratikBilgilerRoute: typeof PratikBilgilerRoute
  UrunlerRoute: typeof UrunlerRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratik-bilgiler': {
      id: '/pratik-bilgiler'
      path: '/pratik-bilgiler'
      fullPath: '/pratik-bilgiler'
      preLoaderRoute: typeof PratikBilgilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmet-bolgeleri': {
      id: '/hizmet-bolgeleri'
      path: '/hizmet-bolgeleri'
      fullPath: '/hizmet-bolgeleri'
      preLoaderRoute: typeof HizmetBolgeleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmet-bolgeleri/$bolge': {
      id: '/hizmet-bolgeleri/$bolge'
      path: '/$bolge'
      fullPath: '/hizmet-bolgeleri/$bolge'
      preLoaderRoute: typeof HizmetBolgeleriBolgeRouteImport
      parentRoute: typeof HizmetBolgeleriRoute
    }
  }
}

interface HizmetBolgeleriRouteChildren {
  HizmetBolgeleriBolgeRoute: typeof HizmetBolgeleriBolgeRoute
}

const HizmetBolgeleriRouteChildren: HizmetBolgeleriRouteChildren = {
  HizmetBolgeleriBolgeRoute: HizmetBolgeleriBolgeRoute,
}

const HizmetBolgeleriRouteWithChildren = HizmetBolgeleriRoute._addFileChildren(
  HizmetBolgeleriRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HizmetBolgeleriRoute: HizmetBolgeleriRouteWithChildren,
  HizmetlerRoute: HizmetlerRoute,
  IletisimRoute: IletisimRoute,
  PratikBilgilerRoute: PratikBilgilerRoute,
  UrunlerRoute: UrunlerRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
